app:
  name: clutchserver

jwt:
  header: Authorization
  expires_in: 999999 # 5 minutes
  mobile_expires_in: 999999 # 10 minutes
  secret: queenvictoria


spring:
  jpa:
    hibernate:
      # possible values: validate | update | create | create-drop
      ddl-auto:  create

   datasource:
       url: ${JDBC_DATABASE_URL}
       username: ${JDBC_DATABASE_USERNAME}
       password: ${JDBC_DATABASE_PASSWORD}


