app:
  name: clutchserver

jwt:
  header: Authorization
  expires_in: 999999 # 5 minutes
  mobile_expires_in: 999999 # 10 minutes
  secret: queenvictoria


spring:
  jpa:
    hibernate:
      # possible values: validate | update | create | create-drop
      ddl-auto:  create-drop


  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}

    #url: jdbc:mysql://localhost:3306/clutchdatabase?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&characterEncoding=UTF-8
    #username: root
    #password: root
    #password: 12345678910111213
