app:
  name: clutchserver

jwt:
  header: Authorization
  expires_in: 9000 # 5 minutes
  mobile_expires_in: 9000 # 10 minutes
  secret: queenvictoria


spring:
  jpa:
    hibernate:
      # possible values: validate | update | create | create-drop
      ddl-auto: create

  datasource:
    url: jdbc:mysql://localhost:3306/clutchdatabase?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    #password: root
    password: 12345678910111213
    driver-class-name: com.mysql.jdbc.Driver
