app:
  name: clutchserver

jwt:
  header: Authorization
  expires_in: 999999 # 5 minutes
  mobile_expires_in: 999999 # 10 minutes
  secret: queenvictoria


spring:
  jpa:
    hibernate:
      # possible values: validate | update | create | create-drop
      ddl-auto:  create-drop


  datasource:
    url: jdbc:mysql://clutchinstance.c4hp6ljob9pu.us-east-2.rds.amazonaws.com:3306/clutch
    username: root
    password: 12345678
    #password: 12345678910111213
    driver-class-name: com.mysql.jdbc.Driver


